server:
  port: 8000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/recamp?characterEncoding=UTF-8&serverTimeZone=Asia/Seoul
    username: root
    password: 1q2w3e4r!
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379

jwt:
  token:
    value: recampauthenticationprivateprojectlocal
    accesstoken:
      expiration: 60000
    refreshtoken:
      expiration: 300000
